# Generated by Django 5.0.3 on 2024-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_team_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
