# Generated by Django 5.0.3 on 2024-03-13 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_team_team_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('team', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_team_shield', to='league.team', verbose_name='Team')),
            ],
        ),
    ]
