# Generated by Django 5.0.2 on 2024-03-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='trainer_id',
            new_name='trainer',
        ),
    ]
