# Generated by Django 5.0.2 on 2024-03-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_message_notice_message_notice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='notification_created_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='session_created_at',
        ),
    ]
