# Generated by Django 5.0.2 on 2024-03-14 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_message_notification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='notification_tittle',
            new_name='notification_title',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='train_session_tittle',
            new_name='train_session_title',
        ),
    ]
