# Generated by Django 5.0.2 on 2024-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_rename_notification_created_at_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
