# Generated by Django 5.0.2 on 2024-03-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_rename_notification_tittle_message_notification_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='train_created_at',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='train_description',
            new_name='session_created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='train_session_title',
            new_name='session_title',
        ),
    ]
