# Generated by Django 5.0.2 on 2024-03-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_rename_train_created_at_message_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='description',
            new_name='session_description',
        ),
    ]
