# Generated by Django 5.0.2 on 2024-04-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_player_parent_alter_player_team'),
        ('session', '0005_alter_message_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=300)),
                ('session_description', models.CharField(blank=True, max_length=300, null=True)),
                ('notification', models.CharField(blank=True, max_length=300, null=True)),
                ('notice', models.CharField(blank=True, max_length=300, null=True)),
                ('event', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('player', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_players_session', to='members.player', verbose_name='Players')),
                ('trainer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_trainers_session', to='members.trainer', verbose_name='Trainer')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
