# Generated by Django 5.0.2 on 2024-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_events_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='day_event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
