# Generated by Django 5.0.2 on 2024-04-01 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_player_parent_alter_player_team'),
        ('session', '0007_events_day_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_players_session', to='members.player', verbose_name='Players'),
        ),
        migrations.AlterField(
            model_name='events',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_trainers_session', to='members.trainer', verbose_name='Trainer'),
        ),
    ]
