# Generated by Django 5.0.2 on 2024-04-13 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_shields'),
        ('session', '0008_alter_events_player_alter_events_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='day_event',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event', models.CharField(max_length=300)),
                ('description_event', models.CharField(max_length=300)),
                ('dateEvent', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_team_foro', to='league.team', verbose_name='Team')),
            ],
        ),
    ]
