# Generated by Django 5.0.2 on 2024-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_remove_events_day_event_remove_events_event_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='dateEvent',
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_time',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
