# Generated by Django 5.0.2 on 2024-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0011_calendar_event_date_alter_calendar_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='description_event',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='event_time',
            field=models.CharField(max_length=300),
        ),
    ]
