# Generated by Django 5.0.2 on 2024-04-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_alter_calendar_description_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='other',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
