# Generated by Django 5.0.2 on 2024-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_events_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color_event',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
