# Generated by Django 5.0.3 on 2024-03-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_team_team_code'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='player',
            name='parent',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_players', to='league.team', verbose_name='Parent'),
        ),
    ]
