# Generated by Django 5.0.3 on 2024-03-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_alter_team_team_code'),
        ('members', '0002_rename_position_player_category_remove_player_parent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.AddField(
            model_name='player',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_parent', to='members.parent', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='get_team', to='league.team', verbose_name='Team'),
        ),
    ]
