# Generated by Django 5.0.3 on 2024-03-08 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_parents_parent_player_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Trainer', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.RemoveField(
            model_name='parent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
