# Generated by Django 5.0.2 on 2024-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_parent_options_alter_trainer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='token_jwt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='token_jwt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
