# Generated by Django 5.0.3 on 2024-03-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_parent_token_jwt_trainer_token_jwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='token_jwt',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='token_jwt',
        ),
    ]
