# Generated by Django 5.0.2 on 2024-03-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_parent_token_jwt_remove_trainer_token_jwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
