# Generated by Django 5.0.2 on 2024-03-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_shields'),
        ('members', '0007_parent_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_trainers', to='members.trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_teams', to='league.team', verbose_name='Team'),
        ),
    ]
