# Generated by Django 5.0.2 on 2024-03-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_parent_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='dni',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='dni',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='dni',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
