# Generated by Django 5.0.2 on 2024-04-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_shields'),
        ('members', '0010_parent_dni_player_dni_trainer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_parent', to='members.parent', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_team', to='league.team', verbose_name='Team'),
        ),
    ]
