# Generated by Django 5.0.2 on 2024-04-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('members', '0011_alter_player_parent_alter_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.AddField(
            model_name='forum',
            name='parent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum',
            name='trainer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.trainer'),
            preserve_default=False,
        ),
    ]
