# Generated by Django 5.0.3 on 2024-04-26 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_user_forum_parent_forum_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='trainer',
        ),
    ]
