# Generated by Django 5.0.2 on 2024-04-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_user_forum_parent_forum_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='trainer',
        ),
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=300),
            preserve_default=300,
        ),
    ]
