# Generated by Django 5.0.2 on 2024-04-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forum_parent_remove_forum_trainer_forum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=300),
            preserve_default=300,
        ),
    ]
